console.log(typeof "Hello")
console.log(typeof 123)
console.log(typeof true)
console.log(typeof false)
console.log(typeof null)
console.log(typeof undefined)
console.log(typeof {})
console.log(typeof [])